ami="ami-0f5e8a042c8bfcd5e"
secret_key = "CZacjVkeog/CujoPs71h2rR9Qs0pzL9HUD5YmFwW"
access_key = "AKIAUPTCMVE5W5RNAI6A"
Name = "AWSWorld"
region = "us-west-1"
instancetype = "t2.micro"
key_name = "Terraformkeys"